In [57]:
import numpy as np

In [58]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexing

In [60]:
arr1[0:,[3,1,2,0,4]] #Ans1

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [61]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row

In [62]:
arr1[::-1,:] #Ans2

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [63]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [64]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2

In [65]:
#Ans3
mean=np.nanmean(arr2)
arr2[np.isnan(arr2)]=mean
arr2

array([[1. , 2. , 4.5],
       [4. , 5. , 6. ],
       [4.5, 4.5, 9. ]])

In [69]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[15, 28, 58,  3],
       [65,  4, 66, 46],
       [59, 88, 90, 46],
       [33, 31, 16, 55],
       [67, 56,  9, 42]])

In [70]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3

In [71]:
arr3[(arr3>25) | (arr3%3==0)] #Ans4

array([15, 28, 58,  3, 65, 66, 46, 59, 88, 90, 46, 33, 31, 55, 67, 56,  9,
       42])

In [0]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

In [ ]:
#Ans5

In [72]:
np.percentile(arr3,10) 

8.5

In [73]:
np.percentile(arr3,25)

25.0

In [74]:
np.percentile(arr3,50)

46.0