In [1]:
import numpy as np

In [10]:
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

## Q1. From arr1 you have to fetch out every alternate column starting from col1

In [11]:
arr1[:,0::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

## Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 

In [12]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [13]:
arr1[0:7:3,0::2]

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [15]:
# Setup for question
# Generating a random numpy array of intergers ranging between 1 and 100
arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[6660, 7461, 9450, 1341,   31],
       [8280, 7187,  614, 2982, 2349]])

Normalization rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

Xchanged=(X−Xmin)/(Xmax−Xmin)

## Q3. Write a code to normalize arr2.

In [16]:
np.percentile(arr1,25)

9.75

In [36]:
# Generating a random numpy array of intergers ranging between 1 and 100
arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[5519, 9062, 9267, 2051, 7852],
       [3589, 4255, 4251, 1475, 4414]])

In [38]:
def normalize(x):
    norm = (x-x.min())/(x.max()-x.min())
    return norm
normalize(arr2)

array([[0.51899384, 0.97369097, 1.        , 0.07392197, 0.81840349],
       [0.2713039 , 0.35677618, 0.35626283, 0.        , 0.37718172]])

## Q4. How would you check if your numpy array has some missing values?

In [39]:
arr2

array([[5519, 9062, 9267, 2051, 7852],
       [3589, 4255, 4251, 1475, 4414]])

In [53]:
np.isnan(arr2)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

# Q5. Write a function which will accept 2 arguments.
First: A 1D numpy array arr
 Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array

 Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [106]:
arr = [12,34,40,7,1,0]
def klargest(arr,n):
    arr.sort(reverse = True) 
    print (arr[n-1]) 
klargest(arr,3)



12
